# Generated by Django 5.0.6 on 2024-07-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
